apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${secret_provider_class_name}
  namespace: nebuly
spec:
  provider: gcp
  secretObjects:
    - secretName: ${secret_provider_class_secret_name}
      type: Opaque
      data:
        - key: ${k8s_secret_key_auth_db_username}
          objectName: auth-db-username
        - key: ${k8s_secret_key_auth_db_password}
          objectName: auth-db-password
        - key: ${k8s_secret_key_analytics_db_password}
          objectName: analytics-db-password
        - key: ${k8s_secret_key_analytics_db_username}
          objectName: analytics-db-username
        - key: ${k8s_secret_key_openai_api_key}
          objectName: openai-api-key
        - key: ${k8s_secret_key_jwt_signing_key}
          objectName: jwt-signing-key
        - key: ${k8s_secret_key_nebuly_client_id}
          objectName: nebuly-client-id
        - key: ${k8s_secret_key_nebuly_client_secret}
          objectName: nebuly-client-secret
        %{ if microsoft_sso_enabled }
        - key: ${k8s_secret_key_microsoft_sso_client_id}
          objectName: microsoft-sso-client-id
        - key: ${k8s_secret_key_microsoft_sso_client_secret}
          objectName: microsoft-sso-client-secret
        %{ endif }
  parameters:
    secrets: |
      - resourceName: ${secret_name_auth_db_username}
        path: auth-db-username
      - resourceName: ${secret_name_auth_db_password}
        path: auth-db-password
      - resourceName: ${secret_name_analytics_db_username}
        path: analytics-db-username
      - resourceName: ${secret_name_analytics_db_password}
        path: analytics-db-password
      - resourceName: ${secret_name_nebuly_client_id}
        path: nebuly-client-id
      - resourceName: ${secret_name_nebuly_client_secret}
        path: nebuly-client-secret
      - resourceName: ${secret_name_openai_api_key}
        path: openai-api-key
      - resourceName: ${secret_name_jwt_signing_key}
        path: jwt-signing-key
      %{ if microsoft_sso_enabled }
      - resourceName: ${secret_name_microsoft_sso_client_id}
        path: microsoft-sso-client-id
      - resourceName: ${secret_name_microsoft_sso_client_secret}
        path: microsoft-sso-client-secret
      %{ endif }
